# Generated by Django 3.2.16 on 2023-01-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='about',
            field=models.CharField(default='I am a customer', max_length=150, null='True'),
        ),
    ]
