# Generated by Django 3.2.16 on 2023-02-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_remove_car_user'),
        ('customer', '0002_alter_customerprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='rented',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.car'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='about',
            field=models.CharField(default='I am a customer', max_length=150, null=True),
        ),
    ]
