# Generated by Django 3.2.16 on 2023-02-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20230221_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='rented',
        ),
    ]
