# Generated by Django 3.2.16 on 2023-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customerprofile_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='credit_rating',
            field=models.IntegerField(null=True),
        ),
    ]
