# Generated by Django 3.2.18 on 2023-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_customerprofile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='credit_rating',
            field=models.IntegerField(default='500', null=True),
        ),
    ]
