# Generated by Django 3.2.16 on 2023-02-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=200)),
                ('Class', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=200)),
                ('Sales_Name', models.CharField(max_length=200)),
                ('Sales_RepNumber', models.IntegerField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReturnDate', models.DateTimeField()),
                ('RentalDate', models.DateTimeField()),
                ('TotalCost', models.IntegerField()),
                ('Car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental.car')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Procedure', models.CharField(max_length=500)),
                ('Mileage', models.IntegerField()),
                ('Repair_Time', models.IntegerField()),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.car')),
            ],
        ),
    ]
