# Generated by Django 3.2.16 on 2023-02-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='Sales_RepNumber',
            field=models.IntegerField(),
        ),
    ]
