# Generated by Django 3.2.16 on 2023-02-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_manufacturer_sales_repnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='User',
        ),
    ]
