# Generated by Django 3.2.16 on 2023-02-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customerprofile_rented'),
        ('rental', '0003_remove_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile'),
        ),
    ]
