# Generated by Django 3.2.18 on 2023-02-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20230221_0635'),
        ('rental', '0004_car_renter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Renter',
        ),
        migrations.RemoveField(
            model_name='maintenanceevent',
            name='Car',
        ),
        migrations.AddField(
            model_name='car',
            name='Maintenance',
            field=models.ManyToManyField(null=True, to='rental.MaintenanceEvent'),
        ),
        migrations.AddField(
            model_name='car',
            name='Manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.manufacturer'),
        ),
        migrations.AddField(
            model_name='maintenanceevent',
            name='RepairNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='ManufacturerName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='Renter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile'),
        ),
        migrations.AlterField(
            model_name='car',
            name='Class',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='Model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='Date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='Mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenanceevent',
            name='Repair_Time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='Country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='Sales_Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='Sales_RepNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='Car',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.car'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='RentalDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='ReturnDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='TotalCost',
            field=models.IntegerField(null=True),
        ),
    ]
