# Generated by Django 3.2.16 on 2023-03-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20230221_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Maintenance',
            field=models.ManyToManyField(to='rental.MaintenanceEvent'),
        ),
    ]
