# Generated by Django 3.2.18 on 2023-03-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_alter_car_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='Car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rental.car'),
        ),
    ]
