# Generated by Django 3.2.18 on 2023-03-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_auto_20230307_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ReturnDate',
            field=models.DateTimeField(null=True),
        ),
    ]
