# Generated by Django 3.2.18 on 2023-03-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_rental_finishedrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Stock_Number',
            field=models.IntegerField(null=True),
        ),
    ]
